### ISSUE TITLE
Link visited problem: SOLVED

### ISSUE THREAD

**Issue by code-reaper08** [Chandu71202/Sample#1]
## Hello @Chandu71202 👋

There are **2 problems** in general with `:visited` and other pseudo CSS classes.

### 1. The sequence of their presence in code:
Here we need to understand that, `:visited` is overridden by other pseudo classes like `:link`, `:hover` and  `:active`. To overcome this we follow a general rule called, **LVHA**, it stands for 

<div align="center">

`Link`-`Visited`-`Hover`-`Active`

</div>

### 2. The working of these Pseudo classes:
This is important and was quite annoying when I found it out. The problem here is pseudo classes like `:link`, `:hover`, `:active` and `:visited` use **Browser history** to determine whether the user visited the `href` or not. So it is important to note that you need to Delete History and try giving different `href`'s if you've already visited them in your recent browser session.

I checked them locally and it works 🎊 

---

Use this CSS rulesets below and try in your local system 😄 

**_HTML_**
```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MyProj</title>
    <link rel="stylesheet" href="index.css" type="text/css">
</head>
<body>
    <div id="topbar">
        <ul>
            <li class="li"><a class="menu-item" href="https://www.yahoo.com">Menu</a></li>
            <li class="li"><a class="menu-item" href="https://www.kotlin.com">Menu</a></li>
            <li class="li"><a class="menu-item"  href="https://www.sample.com">Menu</a></li>

        </ul>
    </div>
</body>
</html>

```
I bet sure you wouldn't have visited these `href`'s 😆 before, so it should work as expected.

**_CSS_**
```
body{
    margin: 0;
}
#topbar{
    background-color: lightblue;
    padding: 10px;
    text-align: center;
}
.li{
    display: inline;
    font-size:x-large;
    padding:106px;
}
.menu-item:link{
    color: green;
}
.menu-item:visited{
    color: blue;
}
.menu-item:hover{
    color: yellow;
}
.menu-item:active{
    color: black;
}

```

Here this order of sequence overcome overriding `:visited` pseudo class.

Cheers !

**Comment by code-reaper08** [comment]
### Use this [link](https://jsfiddle.net/Vishwa_R/p3kbyhxa/2/) to test a running sample @Chandu71202

**Comment by Chandu71202** [comment]
Hey ThankYou  code-reaper08 for clearing this . I think the second case (browsing history) made a trouble. and this LVHA is cool :)
